#!/command/with-contenv bash
cd /home/jovyan
exec 2>&1
# Get the NB_PREFIX value
PREFIX=${NB_PREFIX:-/}
# Update the Nginx config with the actual prefix
sed -i "s|NOTEBOOK_PREFIX|${PREFIX}|g" /etc/nginx/conf.d/default.conf
# Make Nginx run in non-daemon mode
exec nginx -g 'daemon off;'
